Support DNS aliasing for ACME challenges

diff --git a/home/acme/bin/cf_hook b/home/acme/bin/cf_hook
--- a/home/acme/bin/cf_hook
+++ b/home/acme/bin/cf_hook
@@ -7,6 +7,10 @@ set -euo pipefail
 # script runs as.
 umask 0077
 
+reset=$'\e[0m'
+gray=$'\e[90m'
+lblue=$'\e[1;34m'
+
 # Each line in the below file has information about a DNS record this script
 # created but still needs to delete.
 dns_cleanup_path="$BASEDIR/cf_dns_cleanup"
@@ -30,9 +34,6 @@ _clean_dns_record() {
 			-X DELETE > /dev/null
 	fi
 
-	# Get all the DNS record info passed into this function's arguments.
-	local dns_record_info="$*"
-
 	# Use a temporary file for writing to our DNS cleanup file to prevent
 	# corrupting the original in case of a system failure.
 	temp_dns_cleanup_path="$(mktemp)"
@@ -40,7 +41,7 @@ _clean_dns_record() {
 	# Now that the DNS record is deleted, remove it from our DNS cleanup
 	# file. If `grep` returns an error due to finding no matches, instead do
 	# nothing.
-	grep -Fvx "$dns_record_info" "$dns_cleanup_path" || : \
+	grep -Fvx "$dns_record_name $token_value" "$dns_cleanup_path" || : \
 		> "$temp_dns_cleanup_path"
 
 	# Save the DNS cleanup file.
@@ -48,8 +49,12 @@ _clean_dns_record() {
 }
 
 # Deletes any DNS records previously created by this script that never got
-# cleaned up.
+# cleaned up. This is useful when, for example, the container is stopped in the
+# middle of an ACME challenge, leaving `dehydrated` unable to run the cleanup
+# hook, so the ACME DNS records would otherwise stay there forever.
 _clean_old_challenges() {
+	local zone_id="$1"
+
 	# Create our DNS cleanup file if it doesn't already exist.
 	touch "$dns_cleanup_path"
 
@@ -59,7 +64,7 @@ _clean_old_challenges() {
 	while read -ra dns_record_info; do
 		# Pass the words in the array as arguments to our DNS cleanup
 		# function.
-		_clean_dns_record "${dns_record_info[@]}"
+		_clean_dns_record "$zone_id" "${dns_record_info[@]}"
 	done < "$dns_cleanup_path"
 }
 
@@ -70,14 +75,69 @@ deploy_challenge() {
 
 	# Create the `_acme-challenge` DNS record requested by `dehydrated`.
 
-	local zone_id
-	zone_id="$(cf zone_id "$domain")" || exit 1
+	echo "Fetching your Cloudflare zone information..."
 
-	local dns_record_name="_acme-challenge.$domain"
+	local zone_json
+	zone_json="$(cf zone)" || exit 1
+
+	local zone_id
+	zone_id="$(jq -r '.id' <<< "$zone_json")"
+
+	local zone_name
+	zone_name="$(jq -r '.name' <<< "$zone_json")"
+
+	echo "Zone '$zone_name' found."
+
+	# The DNS record Let's Encrypt will read (hence "r") to check for our
+	# ACME token.
+	local r_dns_record_name="_acme-challenge.$domain"
+
+	# The DNS record we'll write (hence "w") the ACME token to.
+	local w_dns_record_name="$r_dns_record_name"
+
+	# Check if the domain being validated (`$domain`) is outside the domain
+	# of the zone our token has access to (`$zone_name`).
+	if [[ ".$domain" != *".$zone_name" ]]; then
+		# Ensure adding the DNS record to the zone will still indirectly
+		# (through a CNAME record) apply to the domain being validated.
+
+		w_dns_record_name="$r_dns_record_name.$zone_name"
+
+		echo "The domain '$domain' being validated is outside the zone '$zone_name' your Cloudflare token has access to. Verifying CNAME..."
+
+		# Get the value of the CNAME record (if there is one).
+		local cname
+		cname="$(
+			cf dns query CNAME "$r_dns_record_name" |
+			jq -r '.Answer[0].data'
+		)" || exit 1
+
+		# Check if the CNAME record (if it exists) doesn't point to the
+		# name of the DNS record we're creating.
+		if [[ "$cname" != "$w_dns_record_name." ]]; then
+			cat <<-END >&2
+			ERROR: Incorrect CNAME! If you want to use a DNS alias, permanently set the following DNS record for ${lblue}$domain${reset}:
+
+			Type: ${lblue}CNAME${reset}
+
+			Name: ${lblue}$r_dns_record_name${reset}
+
+			Target: ${lblue}$w_dns_record_name${reset}
+
+			Proxy status: ${lblue}DNS only${reset}
+
+			${gray}If you don't want to use a DNS alias, ensure your hostname (in \`compose.override.yaml\`) is under the same domain as the zone your Cloudflare API token (in \`.env\`) has DNS editing permissions for.${reset}
+			END
+
+			exit 1
+		fi
+
+		echo "CNAME verified."
+	fi
 
 	local dns_record_comment="This record should be deleted automatically. If it isn't, feel free to delete it."
 
-	local dns_record_data='{"type":"TXT","name":"'"$dns_record_name"'","content":"'"$token_value"'","comment":"'"$dns_record_comment"'"}'
+	local dns_record_data='{"type":"TXT","name":"'"$w_dns_record_name"'","content":"'"$token_value"'","comment":"'"$dns_record_comment"'"}'
 
 	# Use a temporary file for writing to our DNS cleanup file to prevent
 	# corrupting the original in case of a system failure.
@@ -87,10 +147,12 @@ deploy_challenge() {
 	# Save some information about the DNS record we'll create. That way, for
 	# example if the container stops in the middle of the ACME challenge, we
 	# don't lose this information, and we can still remove the record.
-	echo "$zone_id $dns_record_name $token_value" >> "$temp_dns_cleanup_path"
+	echo "$w_dns_record_name $token_value" >> "$temp_dns_cleanup_path"
 
 	# Save the DNS cleanup file.
 	mv -f "$temp_dns_cleanup_path" "$dns_cleanup_path"
+
+	echo "Creating DNS record '$w_dns_record_name'..."
 
 	cf api "/zones/$zone_id/dns_records" \
 		-X POST \
@@ -104,22 +166,28 @@ deploy_challenge() {
 # `dehydrated` runs this after a domain is validated.
 clean_challenge() {
 	# These arguments are passed in by `dehydrated`.
-	local domain="$1" token_value="$3"
+	local token_value="$3"
 
 	local zone_id
-	zone_id="$(cf zone_id "$domain")" || exit 1
+	zone_id="$(cf zone | jq -r '.id')" || exit 1
 
-	local dns_record_name="_acme-challenge.$domain"
+	# Use the token value of the DNS record we're cleaning up to find the
+	# record in our DNS cleanup file.
+	local dns_record_info
+	read -ra dns_record_info < <(
+		grep -F " $token_value" "$dns_cleanup_path"
+	)
 
-	_clean_dns_record "$zone_id" "$dns_record_name" "$token_value"
+	_clean_dns_record "$zone_id" "${dns_record_info[@]}"
 }
 
 # `dehydrated` runs this on each attempt to issue certificates before running
 # anything else in this script.
 startup_hook() {
-	# Delete any DNS records previously created by this script that never
-	# got cleaned up.
-	_clean_old_challenges
+	local zone_id
+	zone_id="$(cf zone | jq -r '.id')" || exit 1
+
+	_clean_old_challenges "$zone_id"
 }
 
 case "$1" in
diff --git a/usr/local/bin/cf b/usr/local/bin/cf
--- a/usr/local/bin/cf
+++ b/usr/local/bin/cf
@@ -40,46 +40,76 @@ api() {
 	echo "$response_json"
 }
 
-# Gets the Cloudflare zone ID for a domain.
-zone_id() {
-	local domain="$1"
-
-	local zone_id
-	zone_id="$(
-		api /zones --url-query "name=$domain" |
-		jq -r '.result[0].id'
+# Gets the JSON value of the zone the Cloudflare API token has access to. If the
+# API token doesn't have access to exactly one zone, this returns an error.
+#
+# Note that which zone this returns can change without restarting the container
+# if the token's permissions are edited in Cloudflare.
+zone() {
+	# Get JSON values for all the zones the token has access to.
+	local zone_jsons
+	zone_jsons="$(
+		api /zones | jq -cr '.result[]'
 	)" || exit 1
 
-	# If no zone is found, try again with one subdomain component removed.
-	# For example, Cloudflare won't find a zone for `mail.example.com`, but
-	# it can find a zone for `example.com`.
-	if [[ "$zone_id" == "null" ]]; then
-		local domain_without_subdomain="${domain#*.}"
-
-		# This is the initial domain from before any subdomain
-		# components were removed.
-		local initial_domain="${INITIAL_DOMAIN:-$domain}"
-
-		# If removing a component from the domain results in a string
-		# with no periods, it's not even a valid domain anymore, so the
-		# failure to find a zone isn't merely a result of a subdomain's
-		# presence.
-		if [[ "$domain_without_subdomain" != *.* ]]; then
-			echo "ERROR: No Cloudflare zone found for domain '$initial_domain'." >&2
-			exit 1
-		fi
-
-		# Call this function again with one subdomain component removed.
-		INITIAL_DOMAIN="$initial_domain" \
-		zone_id "$domain_without_subdomain"
-		return 0
+	# Check if the token doesn't have access to any zones.
+	if [[ -z "$zone_jsons" ]]; then
+		echo "ERROR: Your Cloudflare API token cannot access any zones. Please enable its permission to edit DNS for a zone." >&2
+		exit 1
 	fi
 
-	echo "$zone_id"
+	# Check if the token has access to multiple zones.
+	if [[ "$zone_jsons" == *$'\n'* ]]; then
+		echo "ERROR: Your Cloudflare API token can access multiple zones, which is insecure. Please restrict its permissions so it can only edit DNS for a single zone." >&2
+		exit 1
+	fi
+
+	# Now that we're sure there's only one zone, output it.
+	echo "$zone_jsons"
+}
+
+# Calls one of the below DNS functions.
+dns() {
+	local subcommand="$1"
+	shift
+
+	case "$subcommand" in
+	query | purge)
+		"dns_$subcommand" "$@"
+		;;
+	*)
+		exit 1
+		;;
+	esac
+}
+
+# Makes a query to Cloudflare's DNS.
+dns_query() {
+	local type="$1" name="$2"
+
+	# Refresh Cloudflare's DNS cache for the record we're querying so we get
+	# the most updated answer.
+	cf dns purge "$type" "$name"
+
+	curl -LSs -X GET https://cloudflare-dns.com/dns-query \
+		--url-query "type=$type" \
+		--url-query "name=$name" \
+		-H "Accept: application/dns-json" \
+		--fail-with-body
+}
+
+# Refreshes Cloudflare's DNS cache.
+dns_purge() {
+	local type="$1" domain="$2"
+
+	curl -LSs -X POST https://cloudflare-dns.com/api/v1/purge \
+		--url-query "type=$type" \
+		--url-query "domain=$domain" \
+		--fail-with-body > /dev/null
 }
 
 case "$1" in
-api | zone_id)
+api | zone | dns)
 	"$@"
 	;;
 *)
