Use more concise variable names for record info

diff --git a/home/acme/bin/cf_hook b/home/acme/bin/cf_hook
--- a/home/acme/bin/cf_hook
+++ b/home/acme/bin/cf_hook
@@ -15,20 +15,20 @@ dns_cleanup_path="$BASEDIR/cf_dns_cleanup"
 
 # Deletes a DNS record and removes its information from our DNS cleanup file.
 _clean_dns_record() {
-	local zone_id="$1" dns_record_name="$2" token_value="$3"
+	local zone_id="$1" record_name="$2" token_value="$3"
 
-	local dns_record_id
-	dns_record_id="$(
+	local record_id
+	record_id="$(
 		cf api "/zones/$zone_id/dns_records" \
 			--url-query "type=TXT" \
-			--url-query "name=$dns_record_name" \
+			--url-query "name=$record_name" \
 			--url-query "content=$token_value" \
 		| jq -r '.result[0].id'
 	)"
 
 	# Only try to delete the DNS record if it was found.
-	if [[ "$dns_record_id" != "null" ]]; then
-		cf api "/zones/$zone_id/dns_records/$dns_record_id" \
+	if [[ "$record_id" != "null" ]]; then
+		cf api "/zones/$zone_id/dns_records/$record_id" \
 			-X DELETE > /dev/null
 	fi
 
@@ -40,7 +40,7 @@ _clean_dns_record() {
 	# Now that the DNS record is deleted, remove it from our DNS cleanup
 	# file. If `grep` returns an error due to finding no matches, instead do
 	# nothing.
-	grep -Fvxe "$dns_record_name $token_value" -- "$dns_cleanup_path" || : \
+	grep -Fvxe "$record_name $token_value" -- "$dns_cleanup_path" || : \
 		> "$temp_dns_cleanup_path"
 
 	# Save the DNS cleanup file.
@@ -59,11 +59,11 @@ _clean_old_challenges() {
 
 	# Read each line from our DNS cleanup file, and split each line's words
 	# into a Bash array.
-	local dns_record_info
-	while read -ra dns_record_info; do
+	local record_info
+	while read -ra record_info; do
 		# Pass the words in the array as arguments to our DNS cleanup
 		# function.
-		_clean_dns_record "$zone_id" "${dns_record_info[@]}"
+		_clean_dns_record "$zone_id" "${record_info[@]}"
 	done < "$dns_cleanup_path"
 }
 
@@ -85,10 +85,10 @@ deploy_challenge() {
 
 	# The DNS record Let's Encrypt will read (hence "r") to check for our
 	# ACME token.
-	local r_dns_record_name="_acme-challenge.$domain"
+	local r_record_name="_acme-challenge.$domain"
 
 	# The DNS record we'll write (hence "w") the ACME token to.
-	local w_dns_record_name="$r_dns_record_name"
+	local w_record_name="$r_record_name"
 
 	# Check if the domain being validated (`$domain`) is outside the domain
 	# of the zone our token has access to (`$zone_name`).
@@ -96,28 +96,28 @@ deploy_challenge() {
 		# Ensure adding the DNS record to the zone will still indirectly
 		# (through a CNAME record) apply to the domain being validated.
 
-		w_dns_record_name="$r_dns_record_name.$zone_name"
+		w_record_name="$r_record_name.$zone_name"
 
 		printf '%s\n' "The domain '$domain' being validated is outside the zone '$zone_name' your Cloudflare token has access to. Verifying CNAME..."
 
 		# Get the value of the CNAME record (if it exists).
 		local cname
 		cname="$(
-			cf dns query CNAME "$r_dns_record_name" \
+			cf dns query CNAME "$r_record_name" \
 			| jq -r '.Answer[0].data'
 		)"
 
 		# Check if the CNAME record (if it exists) doesn't point to the
 		# name of the DNS record we're creating.
-		if [[ "$cname" != "$w_dns_record_name." ]]; then
+		if [[ "$cname" != "$w_record_name." ]]; then
 			cat <<-END >&2
 			ERROR: Incorrect CNAME! If you want to use a DNS alias, permanently set the following DNS record for ${lblue}$domain${reset}:
 
 			Type: ${lblue}CNAME${reset}
 
-			Name: ${lblue}$r_dns_record_name${reset}
+			Name: ${lblue}$r_record_name${reset}
 
-			Target: ${lblue}$w_dns_record_name${reset}
+			Target: ${lblue}$w_record_name${reset}
 
 			Proxy status: ${lblue}DNS only${reset}
 
@@ -138,41 +138,40 @@ deploy_challenge() {
 	# Save some information about the DNS record we'll create. That way, for
 	# example if the container stops in the middle of the ACME challenge, we
 	# don't lose this information, and we can still remove the record.
-	printf '%s\n' "$w_dns_record_name $token_value" \
-		>> "$temp_dns_cleanup_path"
+	printf '%s\n' "$w_record_name $token_value" >> "$temp_dns_cleanup_path"
 
 	# Save the DNS cleanup file.
 	mv -f -- "$temp_dns_cleanup_path" "$dns_cleanup_path"
 
 	# Try requesting the DNS record we would otherwise create to ensure it
 	# doesn't already exist. If it doesn't exist, this will be `null`.
-	local dns_record_json
-	dns_record_json="$(
+	local record_json
+	record_json="$(
 		cf api "/zones/$zone_id/dns_records" \
 			--url-query "type=TXT" \
-			--url-query "name=$w_dns_record_name" \
+			--url-query "name=$w_record_name" \
 			--url-query "content=$token_value" \
 		| jq '.result[0]'
 	)"
 
 	# Check if the record already exists.
-	if [[ "$dns_record_json" != "null" ]]; then
-		printf '%s\n' "DNS record '$w_dns_record_name' with correct content already exists."
+	if [[ "$record_json" != "null" ]]; then
+		printf '%s\n' "DNS record '$w_record_name' with correct content already exists."
 
 		return 0
 	fi
 
 	# The record doesn't already exist, so create it.
 
-	printf '%s\n' "Creating DNS record '$w_dns_record_name'..."
+	printf '%s\n' "Creating DNS record '$w_record_name'..."
 
-	local dns_record_comment="This record should be deleted automatically. If it isn't, feel free to delete it."
-	local dns_record_data='{"type":"TXT","name":"'"$w_dns_record_name"'","content":"'"$token_value"'","comment":"'"$dns_record_comment"'"}'
+	local record_comment="This record should be deleted automatically. If it isn't, feel free to delete it."
+	local record_data='{"type":"TXT","name":"'"$w_record_name"'","content":"'"$token_value"'","comment":"'"$record_comment"'"}'
 
 	cf api "/zones/$zone_id/dns_records" \
 		-X POST \
 		-H "Content-Type: application/json" \
-		--data-raw "$dns_record_data" > /dev/null
+		--data-raw "$record_data" > /dev/null
 
 	# Reset Bash's timer to 0. It will count up from here.
 	SECONDS=0
@@ -192,16 +191,16 @@ deploy_challenge() {
 		# Get a list of all the DNS record data under this record name.
 		# Remove quotes because quotes are allowed around parts of a TXT
 		# record's data.
-		local dns_record_answers
-		dns_record_answers="$(
-			cf dns query TXT "$w_dns_record_name" \
+		local record_answers
+		record_answers="$(
+			cf dns query TXT "$w_record_name" \
 			| jq -r '.Answer[]?.data' \
 			| tr -d '"'
 		)"
 
 		# If any of the results match the DNS record we created, we can
 		# stop checking for our DNS record.
-		if grep -Fqxe "$token_value" <<< "$dns_record_answers"; then
+		if grep -Fqxe "$token_value" <<< "$record_answers"; then
 			printf '%s\n' "Updated DNS record found."
 			break
 		fi
@@ -211,7 +210,7 @@ deploy_challenge() {
 			exit 1
 		fi
 
-		printf '%s\n' "DNS update for record '$w_dns_record_name' not found yet. Waiting $dns_sleep_seconds more seconds..."
+		printf '%s\n' "DNS update for record '$w_record_name' not found yet. Waiting $dns_sleep_seconds more seconds..."
 	done
 }
 
@@ -225,14 +224,14 @@ clean_challenge() {
 
 	# Use the token value of the DNS record we're cleaning up to find the
 	# record in our DNS cleanup file.
-	local dns_record_info
-	dns_record_info=$(grep -Fe " $token_value" -- "$dns_cleanup_path")
+	local record_info
+	record_info=$(grep -Fe " $token_value" -- "$dns_cleanup_path")
 
 	# Split the record info on whitespace into an array so its values can be
 	# passed as separate arguments to the below function call.
-	read -ra dns_record_info <<< "$dns_record_info"
+	read -ra record_info <<< "$record_info"
 
-	_clean_dns_record "$zone_id" "${dns_record_info[@]}"
+	_clean_dns_record "$zone_id" "${record_info[@]}"
 }
 
 # `dehydrated` runs this on each attempt to issue certificates before running
diff --git a/usr/local/bin/check_sender_dns b/usr/local/bin/check_sender_dns
--- a/usr/local/bin/check_sender_dns
+++ b/usr/local/bin/check_sender_dns
@@ -106,20 +106,20 @@ _check_dkim() {
 
 	# This is our original DKIM record that the sender domains's DKIM record
 	# should point to.
-	local source_dns_record_name="$selector._domainkey.$source_domain"
+	local source_record_name="$selector._domainkey.$source_domain"
 
 	# The name of the DNS record we're checking.
-	local dns_record_name="$selector._domainkey.$sender_domain"
+	local record_name="$selector._domainkey.$sender_domain"
 
 	# If the DKIM DNS record we're checking is already the source record,
 	# there's no need to ensure the former is an alias of the latter.
-	if [[ "$dns_record_name" == "$source_dns_record_name" ]]; then
+	if [[ "$record_name" == "$source_record_name" ]]; then
 		return 0
 	fi
 
 	# This variable will hold information for the DNS record we're checking.
 	# If no such record exists, this will be empty.
-	local dns_record_json=
+	local record_json=
 
 	# This variable will hold the value of the DNS record we're checking. If
 	# no such record exists, this will be empty.
@@ -130,17 +130,17 @@ _check_dkim() {
 	# provides more information about the records that we might need later.
 	# If we don't have API access, get it using a DNS query.
 	if [[ "$can_access_dns" ]]; then
-		dns_record_json="$(
+		record_json="$(
 			cf api "/zones/$zone_id/dns_records" \
 				--url-query "type=CNAME" \
-				--url-query "name=$dns_record_name" \
+				--url-query "name=$record_name" \
 			| jq -c '.result[]'
 		)"
 
-		cname="$(printf '%s\n' "$dns_record_json" | jq -r '.content')"
+		cname="$(printf '%s\n' "$record_json" | jq -r '.content')"
 	else
 		cname="$(
-			cf dns query CNAME "$dns_record_name" \
+			cf dns query CNAME "$record_name" \
 			| jq -r '.Answer[].data'
 		)"
 
@@ -151,11 +151,11 @@ _check_dkim() {
 	fi
 
 	# This will be the value the sender domain's DKIM record should have.
-	local correct_cname="$source_dns_record_name"
+	local correct_cname="$source_record_name"
 
-	_sync_dns_record DKIM CNAME "$dns_record_name" \
+	_sync_dns_record DKIM CNAME "$record_name" \
 		"$cname" "$correct_cname" \
-		"$dns_record_json"
+		"$record_json"
 }
 
 # Ensures the sender's SPF record includes our server's.
@@ -163,20 +163,20 @@ _check_spf() {
 	# This is our original SPF record that sender's SPF record should
 	# include. The name of this record is chosen in our `check_dns` script,
 	# where the record is originally created.
-	local source_dns_record_name="$source_domain"
+	local source_record_name="$source_domain"
 
 	# The name of the DNS record we're checking.
-	local dns_record_name="$sender_domain"
+	local record_name="$sender_domain"
 
 	# If the SPF DNS record we're checking is already the source record,
 	# there's no need to ensure the former includes the latter.
-	if [[ "$dns_record_name" == "$source_dns_record_name" ]]; then
+	if [[ "$record_name" == "$source_record_name" ]]; then
 		return 0
 	fi
 
 	# This variable will hold information for the SPF record we're checking.
 	# If no such record exists, this will be empty.
-	local dns_record_json=
+	local record_json=
 
 	# This variable will hold the value of the SPF record we're checking. If
 	# no such record exists, this will be empty.
@@ -187,11 +187,9 @@ _check_spf() {
 	# provides more information about the records that we might need later.
 	# If we don't have API access, get it using a DNS query.
 	if [[ "$can_access_dns" ]]; then
-		dns_record_json="$(get_spf_record "$dns_record_name")"
+		record_json="$(get_spf_record "$record_name")"
 
-		spf_data="$(
-			printf '%s\n' "$dns_record_json" | jq -r '.content'
-		)"
+		spf_data="$(printf '%s\n' "$record_json" | jq -r '.content')"
 	else
 		# To get the SPF value, get all the TXT record values under the
 		# sender's domain, remove quotes because quotes are allowed
@@ -200,7 +198,7 @@ _check_spf() {
 		# according to RFC 7208 (section 12). If none are found, do
 		# nothing instead of letting `grep` exit with an error.
 		spf_data="$(
-			cf dns query TXT "$dns_record_name" \
+			cf dns query TXT "$record_name" \
 			| jq -r '.Answer[]?.data' \
 			| tr -d '"' \
 			| { grep -Ei '^v=spf1( |$)' || :; }
@@ -208,7 +206,7 @@ _check_spf() {
 
 		# Check if there are multiple SPF records.
 		if [[ "$spf_data" == *$'\n'* ]]; then
-			printf '%s\n' "ERROR: Multiple TXT DNS records starting with 'v=spf1' found at '$dns_record_name', which is not allowed." >&2
+			printf '%s\n' "ERROR: Multiple TXT DNS records starting with 'v=spf1' found at '$record_name', which is not allowed." >&2
 			exit 1
 		fi
 	fi
@@ -221,7 +219,7 @@ _check_spf() {
 
 	# An SPF term that includes our server's own SPF policy into another
 	# domain's SPF policy.
-	local include="include:$source_dns_record_name"
+	local include="include:$source_record_name"
 
 	# If the sender domain's SPF policy doesn't include our server's own SPF
 	# policy, include it so we're allowed to send mail for that domain.
@@ -242,19 +240,19 @@ _check_spf() {
 		printf '%s\n' "$correct_spf_data" | sed -E 's/ [+-?~]?all$//gi'
 	) -all"
 
-	_sync_dns_record SPF TXT "$dns_record_name" \
+	_sync_dns_record SPF TXT "$record_name" \
 		"$spf_data" "$correct_spf_data" \
-		"$dns_record_json"
+		"$record_json"
 }
 
 # Ensures the sender's DMARC record is set up correctly.
 _check_dmarc() {
 	# The name of the DMARC record we're checking.
-	local dns_record_name="_dmarc.$sender_domain"
+	local record_name="_dmarc.$sender_domain"
 
 	# This variable will hold information for the DMARC record we're
 	# checking. If no such record exists, this will be empty.
-	local dns_record_json=
+	local record_json=
 
 	# This variable will hold the value of the DMARC record we're checking.
 	# If no such record exists, this will be empty.
@@ -275,16 +273,14 @@ _check_dmarc() {
 		# DMARC record name. Then filter the results for just the
 		# records with the correct DMARC version according to RFC 7489
 		# (section 6.4).
-		dns_record_json="$(
+		record_json="$(
 			cf api "/zones/$zone_id/dns_records" \
 				--url-query "type=TXT" \
-				--url-query "name=$dns_record_name" \
+				--url-query "name=$record_name" \
 			| jq -c ".result[] | select(.content | test(\"^$v_tag_pattern\"))"
 		)"
 
-		dmarc_data="$(
-			printf '%s\n' "$dns_record_json" | jq -r '.content'
-		)"
+		dmarc_data="$(printf '%s\n' "$record_json" | jq -r '.content')"
 	else
 		# To get the DMARC value, get all the TXT record values under
 		# the sender's domain, remove quotes because quotes are allowed
@@ -293,7 +289,7 @@ _check_dmarc() {
 		# according to RFC 7489 (section 6.4). If none are found, do
 		# nothing instead of letting `grep` exit with an error.
 		dmarc_data="$(
-			cf dns query TXT "$dns_record_name" \
+			cf dns query TXT "$record_name" \
 			| jq -r '.Answer[]?.data' \
 			| tr -d '"' \
 			| { grep "^$v_tag_pattern" || :; }
@@ -303,7 +299,7 @@ _check_dmarc() {
 
 	# Check if there are multiple DMARC records.
 	if [[ "$dmarc_data" == *$'\n'* ]]; then
-		printf '%s\n' "ERROR: Multiple TXT DNS records starting with 'v=DMARC1;' found at '$dns_record_name', which is not allowed." >&2
+		printf '%s\n' "ERROR: Multiple TXT DNS records starting with 'v=DMARC1;' found at '$record_name', which is not allowed." >&2
 		exit 1
 	fi
 
@@ -339,9 +335,9 @@ _check_dmarc() {
 		"
 	)"
 
-	_sync_dns_record DMARC TXT "$dns_record_name" \
+	_sync_dns_record DMARC TXT "$record_name" \
 		"$dmarc_data" "$correct_dmarc_data" \
-		"$dns_record_json"
+		"$record_json"
 }
 
 # Ensure the sender's domain points to both of our DKIM keys.
diff --git a/usr/local/bin/get_spf_record b/usr/local/bin/get_spf_record
--- a/usr/local/bin/get_spf_record
+++ b/usr/local/bin/get_spf_record
@@ -4,7 +4,7 @@
 set -euo pipefail
 
 # The specified DNS record name to search for SPF records at.
-dns_record_name="$1"
+record_name="$1"
 
 # Fetch our Cloudflare zone information.
 zone_id="$(cf zone | jq -r '.id')"
@@ -15,24 +15,24 @@ zone_id="$(cf zone | jq -r '.id')"
 # To find the SPF records, query for all TXT records at the specified name. Then
 # filter the results for just the records with the correct SPF version according
 # to RFC 7208 (section 12).
-dns_record_jsons="$(
+record_jsons="$(
 	cf api "/zones/$zone_id/dns_records" \
 		--url-query "type=TXT" \
-		--url-query "name=$dns_record_name" \
+		--url-query "name=$record_name" \
 	| jq -c '.result[] | select(.content | test("^v=spf1( |$)"; "i"))'
 )"
 
 # If there are multiple SPF records, exit with an error because it's invalid to
 # have multiple SPF records with the same name.
-if [[ "$dns_record_jsons" == *$'\n'* ]]; then
-	printf '%s\n' "ERROR: Multiple TXT DNS records starting with 'v=spf1' found at '$dns_record_name', which is not allowed." >&2
+if [[ "$record_jsons" == *$'\n'* ]]; then
+	printf '%s\n' "ERROR: Multiple TXT DNS records starting with 'v=spf1' found at '$record_name', which is not allowed." >&2
 	exit 1
 fi
 
 # If there are no SPF records, exit with no output.
-if [[ ! "$dns_record_jsons" ]]; then
+if [[ ! "$record_jsons" ]]; then
 	exit 0
 fi
 
 # There is exactly one SPF record, so output it.
-printf '%s\n' "$dns_record_jsons"
+printf '%s\n' "$record_jsons"
