Fix misinterpretation of positional arguments If a variable passed into a command starts with `-`, its content is interpreted as options rather than as positional arguments. Using `--` generally stops further arguments from being interpreted as options. I use it even when the variable doesn't currently start with `-` for the sake of defensive programming. I don't want to make a case-by-case judgment about whether it's necessary, because I am prone to bad judgments, and the case can change after a refactor.
`echo` takes `--` literally, so I'm probably just going to use `printf`
everywhere instead for consistency from now on, since it doesn't have
that problem (as well as many others).

diff --git a/home/acme/bin/cf_hook b/home/acme/bin/cf_hook
--- a/home/acme/bin/cf_hook
+++ b/home/acme/bin/cf_hook
@@ -41,11 +41,11 @@ _clean_dns_record() {
 	# Now that the DNS record is deleted, remove it from our DNS cleanup
 	# file. If `grep` returns an error due to finding no matches, instead do
 	# nothing.
-	grep -Fvx "$dns_record_name $token_value" "$dns_cleanup_path" || : \
+	grep -Fvx -- "$dns_record_name $token_value" "$dns_cleanup_path" || : \
 		> "$temp_dns_cleanup_path"
 
 	# Save the DNS cleanup file.
-	mv -f "$temp_dns_cleanup_path" "$dns_cleanup_path"
+	mv -f -- "$temp_dns_cleanup_path" "$dns_cleanup_path"
 }
 
 # Deletes any DNS records previously created by this script that never got
@@ -56,7 +56,7 @@ _clean_old_challenges() {
 	local zone_id="$1"
 
 	# Create our DNS cleanup file if it doesn't already exist.
-	touch "$dns_cleanup_path"
+	touch -- "$dns_cleanup_path"
 
 	# Read each line from our DNS cleanup file, and split each line's words
 	# into a Bash array.
@@ -75,7 +75,7 @@ deploy_challenge() {
 
 	# Create the `_acme-challenge` DNS record requested by `dehydrated`.
 
-	echo "Fetching your Cloudflare zone information..."
+	printf '%s\n' "Fetching your Cloudflare zone information..."
 
 	local zone_json
 	zone_json="$(cf zone)" || exit 1
@@ -86,7 +86,7 @@ deploy_challenge() {
 	local zone_name
 	zone_name="$(jq -r '.name' <<< "$zone_json")"
 
-	echo "Zone '$zone_name' found."
+	printf '%s\n' "Zone '$zone_name' found."
 
 	# The DNS record Let's Encrypt will read (hence "r") to check for our
 	# ACME token.
@@ -103,7 +103,7 @@ deploy_challenge() {
 
 		w_dns_record_name="$r_dns_record_name.$zone_name"
 
-		echo "The domain '$domain' being validated is outside the zone '$zone_name' your Cloudflare token has access to. Verifying CNAME..."
+		printf '%s\n' "The domain '$domain' being validated is outside the zone '$zone_name' your Cloudflare token has access to. Verifying CNAME..."
 
 		# Get the value of the CNAME record (if there is one).
 		local cname
@@ -132,7 +132,7 @@ deploy_challenge() {
 			exit 1
 		fi
 
-		echo "CNAME verified."
+		printf '%s\n' "CNAME verified."
 	fi
 
 	local dns_record_comment="This record should be deleted automatically. If it isn't, feel free to delete it."
@@ -142,17 +142,18 @@ deploy_challenge() {
 	# Use a temporary file for writing to our DNS cleanup file to prevent
 	# corrupting the original in case of a system failure.
 	temp_dns_cleanup_path="$(mktemp)"
-	cat "$dns_cleanup_path" > "$temp_dns_cleanup_path"
+	cat -- "$dns_cleanup_path" > "$temp_dns_cleanup_path"
 
 	# Save some information about the DNS record we'll create. That way, for
 	# example if the container stops in the middle of the ACME challenge, we
 	# don't lose this information, and we can still remove the record.
-	echo "$w_dns_record_name $token_value" >> "$temp_dns_cleanup_path"
+	printf '%s\n' "$w_dns_record_name $token_value" \
+		>> "$temp_dns_cleanup_path"
 
 	# Save the DNS cleanup file.
-	mv -f "$temp_dns_cleanup_path" "$dns_cleanup_path"
+	mv -f -- "$temp_dns_cleanup_path" "$dns_cleanup_path"
 
-	echo "Creating DNS record '$w_dns_record_name'..."
+	printf '%s\n' "Creating DNS record '$w_dns_record_name'..."
 
 	cf api "/zones/$zone_id/dns_records" \
 		-X POST \
@@ -168,11 +169,11 @@ deploy_challenge() {
 	# Give up checking after this duration.
 	local dns_timeout_seconds=1200
 
-	echo "Waiting $dns_sleep_seconds seconds for your DNS to update..."
+	printf '%s\n' "Waiting $dns_sleep_seconds seconds for your DNS to update..."
 
 	# Repeatedly check our DNS until we ensure our new record is there.
 	while true; do
-		sleep "$dns_sleep_seconds"
+		sleep -- "$dns_sleep_seconds"
 
 		# Get a list of all the DNS record data under this record name.
 		# Remove quotes because quotes are allowed around a TXT record's
@@ -186,17 +187,17 @@ deploy_challenge() {
 
 		# If any of the results match the DNS record we created, we can
 		# stop checking for our DNS record.
-		if grep -Fqx "$token_value" <<< "$dns_record_answers"; then
-			echo "Updated DNS record found."
+		if grep -Fqx -- "$token_value" <<< "$dns_record_answers"; then
+			printf '%s\n' "Updated DNS record found."
 			break
 		fi
 
 		if [[ "$SECONDS" -gt "$dns_timeout_seconds" ]]; then
-			echo "Timed out. DNS updates shouldn't take this long, so something is probably wrong." >&2
+			printf '%s\n' "Timed out. DNS updates shouldn't take this long, so something is probably wrong." >&2
 			exit 1
 		fi
 
-		echo "DNS update for record '$r_dns_record_name' not found yet. Waiting $dns_sleep_seconds more seconds..."
+		printf '%s\n' "DNS update for record '$r_dns_record_name' not found yet. Waiting $dns_sleep_seconds more seconds..."
 	done
 }
 
@@ -212,7 +213,7 @@ clean_challenge() {
 	# record in our DNS cleanup file.
 	local dns_record_info
 	read -ra dns_record_info < <(
-		grep -F " $token_value" "$dns_cleanup_path"
+		grep -F -- " $token_value" "$dns_cleanup_path"
 	)
 
 	_clean_dns_record "$zone_id" "${dns_record_info[@]}"
diff --git a/usr/local/bin/cf b/usr/local/bin/cf
--- a/usr/local/bin/cf
+++ b/usr/local/bin/cf
@@ -20,15 +20,16 @@ api() {
 	response_json="$(
 		# Make the HTTP request to Cloudflare's API using `curl`, with
 		# all of this function's arguments passed in.
-		curl -LSs "$cf_api_base_url$path" \
+		curl -LSs \
 			-H "Authorization: Bearer $cf_api_token" \
-			"$@"
+			"$@" \
+			-- "$cf_api_base_url$path"
 	)" || exit 1
 
 	# Output any errors from the API response.
 	jq -cr '.errors[]' <<< "$response_json" |
 	while read -r error; do
-		echo "ERROR (Cloudflare API): $error" >&2
+		printf '%s\n' "ERROR (Cloudflare API): $error" >&2
 	done
 
 	# If the request wasn't successful, exit the script.
@@ -37,7 +38,7 @@ api() {
 	fi
 
 	# The request was successful, so output the response JSON.
-	echo "$response_json"
+	printf '%s\n' "$response_json"
 }
 
 # Gets the JSON value of the zone the Cloudflare API token has access to. If the
@@ -54,18 +55,18 @@ zone() {
 
 	# Check if the token doesn't have access to any zones.
 	if [[ -z "$zone_jsons" ]]; then
-		echo "ERROR: Your Cloudflare API token cannot access any zones. Please enable its permission to edit DNS for a zone." >&2
+		printf '%s\n' "ERROR: Your Cloudflare API token cannot access any zones. Please enable its permission to edit DNS for a zone." >&2
 		exit 1
 	fi
 
 	# Check if the token has access to multiple zones.
 	if [[ "$zone_jsons" == *$'\n'* ]]; then
-		echo "ERROR: Your Cloudflare API token can access multiple zones, which is insecure. Please restrict its permissions so it can only edit DNS for a single zone." >&2
+		printf '%s\n' "ERROR: Your Cloudflare API token can access multiple zones, which is insecure. Please restrict its permissions so it can only edit DNS for a single zone." >&2
 		exit 1
 	fi
 
 	# Now that we're sure there's only one zone, output it.
-	echo "$zone_jsons"
+	printf '%s\n' "$zone_jsons"
 }
 
 # Calls one of the below DNS functions.
