Start error messages with "ERROR:"

diff --git a/home/acme/bin/cf_hook b/home/acme/bin/cf_hook
--- a/home/acme/bin/cf_hook
+++ b/home/acme/bin/cf_hook
@@ -208,7 +208,7 @@ deploy_challenge() {
 		fi
 
 		if [[ "$SECONDS" -gt "$dns_timeout_seconds" ]]; then
-			printf '%s\n' "Timed out. DNS updates shouldn't take this long, so something is probably wrong." >&2
+			printf '%s\n' "ERROR: Timed out. DNS updates shouldn't take this long, so something is probably wrong." >&2
 			exit 1
 		fi
 
diff --git a/usr/local/bin/check_dns b/usr/local/bin/check_dns
--- a/usr/local/bin/check_dns
+++ b/usr/local/bin/check_dns
@@ -17,7 +17,7 @@ _check_hostname_spf() {
 	# If no IPs are found, something is wrong, and we won't be able to add
 	# this server as an allowed sender in our SPF record.
 	if [[ ! "$ipv4$ipv6" ]]; then
-		printf '%s\n' "Could not obtain your public IP address (to include in your SPF record)." >&2
+		printf '%s\n' "ERROR: Could not obtain your public IP address (to include in your SPF record)." >&2
 		return 1
 	fi
 
diff --git a/usr/local/bin/user b/usr/local/bin/user
--- a/usr/local/bin/user
+++ b/usr/local/bin/user
@@ -48,14 +48,13 @@ add() {
 
 	# Ensure the address doesn't already exist before adding it.
 	if user exists "$address"; then
-		printf '%s\n' "Address '$address' already exists in database." \
-			>&2
+		printf '%s\n' "ERROR: Address '$address' already exists in database." >&2
 		exit 1
 	fi
 
 	# Check if the specified address is invalid.
 	if [[ "$address" != *"@"* ]]; then
-		printf '%s\n' "Invalid address: $address" >&2
+		printf '%s\n' "ERROR: Invalid address: $address" >&2
 		exit 1
 	fi
 
@@ -125,7 +124,7 @@ remove() {
 
 	# Ensure the address exists before removing it.
 	if ! user exists "$address"; then
-		printf '%s\n' "Address '$address' not found in database." >&2
+		printf '%s\n' "ERROR: Address '$address' not found in database." >&2
 		exit 1
 	fi
 
