Slightly improve `acme.sh`'s fault tolerance

diff --git a/home/acme-sh/bin/issue b/home/acme-sh/bin/issue
--- a/home/acme-sh/bin/issue
+++ b/home/acme-sh/bin/issue
@@ -16,6 +16,21 @@ cf_api_token="$(cat /run/secrets/CF_API_TOKEN)"
 # Docker volume defined in `compose.yaml`.
 postfix_tls_path=/etc/postfix/smtpd_tls_chain_files
 
+# If `acme.sh` never gave Postfix this TLS file, a previous attempt of `acme.sh`
+# failed partway, but `acme.sh` might think it completed successfully if a TLS
+# certificate was saved in its directory before the failure, so it'll never
+# complete the attempt and give Postfix its copy of the certificate. Wiping
+# `acme.sh`'s save directory clean makes it issue a new certificate next time.
+# That way, Postfix can get its copy.
+if ! [ -s "$postfix_tls_path/key.pem" ]; then
+	rm -rf ~/.acme.sh/*
+
+	# Since we just reset all of `acme.sh`'s data, set its default
+	# certificate authority to Let's Encrypt again.
+	# TODO: Remove `_test`.
+	acme.sh --set-default-ca --server letsencrypt_test
+fi
+
 # * Use `acme.sh` to issue a new TLS certificate.
 # * Use our domain's DNS records in Cloudflare to prove to Let's Encrypt that we
 #   own the domain we're requesting a certificate for.
@@ -39,6 +54,8 @@ acme.sh \
 	# example due to existing certificates not needing renewal yet.
 	:
 
-# Exit this script if the above files failed to generate, with a nice error
-# message generated by `ls`.
-ls "$postfix_tls_path/key.pem" 1> /dev/null
+# If the final output files failed to generate, then exit with an error.
+if ! [ -s "$postfix_tls_path/key.pem" ]; then
+	echo "TLS certificate issuing failed." >&2
+	exit 1
+fi
